import { Injectable } from "@angular/core";
import { IPokemon } from "./pokemon";

@Injectable({
  providedIn: 'root'
})
export class PokemonService {
  getPokemon(): IPokemon[] {
    return [
      {
        "Number": 1,
        "Name": "Bulbasaur",
        "HD": 6,
        "Hp": 24,
        "Type1": "Grass",
        "Type2": "Poison",
        "Health": 9,
        "Attack": 10,
        "Defense": 10,
        "Special": 13,
        "SplDef": 13,
        "Speed": 9,
        "Hp__1": -1,
        "Atk": 0,
        "Def": 0,
        "Spl": 1,
        "SDf": 1,
        "Spd": -1
      },
      {
        "Number": 2,
        "Name": "Ivysaur",
        "HD": 9,
        "Hp": 54,
        "Type1": "Grass",
        "Type2": "Poison",
        "Health": 12,
        "Attack": 12,
        "Defense": 13,
        "Special": 16,
        "SplDef": 16,
        "Speed": 12,
        "Hp__1": 1,
        "Atk": 1,
        "Def": 1,
        "Spl": 3,
        "SDf": 3,
        "Spd": 1
      },
      {
        "Number": 3,
        "Name": "Venusaur",
        "HD": 14,
        "Hp": 112,
        "Type1": "Grass",
        "Type2": "Poison",
        "Health": 16,
        "Attack": 16,
        "Defense": 17,
        "Special": 20,
        "SplDef": 20,
        "Speed": 16,
        "Hp__1": 3,
        "Atk": 3,
        "Def": 3,
        "Spl": 5,
        "SDf": 5,
        "Spd": 3
      },
      {
        "Number": 4,
        "Name": "Charmander",
        "HD": 5,
        "Hp": 20,
        "Type1": "Fire",
        "Type2": "",
        "Health": 8,
        "Attack": 10,
        "Defense": 9,
        "Special": 12,
        "SplDef": 10,
        "Speed": 13,
        "Hp__1": -1,
        "Atk": 0,
        "Def": -1,
        "Spl": 1,
        "SDf": 0,
        "Spd": 1
      },
      {
        "Number": 5,
        "Name": "Charmeleon",
        "HD": 9,
        "Hp": 54,
        "Type1": "Fire",
        "Type2": "",
        "Health": 12,
        "Attack": 13,
        "Defense": 12,
        "Special": 16,
        "SplDef": 13,
        "Speed": 16,
        "Hp__1": 1,
        "Atk": 1,
        "Def": 1,
        "Spl": 3,
        "SDf": 1,
        "Spd": 3
      },
      {
        "Number": 6,
        "Name": "Charizard",
        "HD": 14,
        "Hp": 112,
        "Type1": "Fire",
        "Type2": "Flying",
        "Health": 16,
        "Attack": 17,
        "Defense": 16,
        "Special": 22,
        "SplDef": 17,
        "Speed": 20,
        "Hp__1": 3,
        "Atk": 3,
        "Def": 3,
        "Spl": 6,
        "SDf": 3,
        "Spd": 5
      },
      {
        "Number": 7,
        "Name": "Squirtle",
        "HD": 5,
        "Hp": 20,
        "Type1": "Water",
        "Type2": "",
        "Health": 9,
        "Attack": 10,
        "Defense": 13,
        "Special": 10,
        "SplDef": 13,
        "Speed": 9,
        "Hp__1": -1,
        "Atk": 0,
        "Def": 1,
        "Spl": 0,
        "SDf": 1,
        "Spd": -1
      },
      {
        "Number": 8,
        "Name": "Wartortle",
        "HD": 9,
        "Hp": 54,
        "Type1": "Water",
        "Type2": "",
        "Health": 12,
        "Attack": 13,
        "Defense": 16,
        "Special": 13,
        "SplDef": 16,
        "Speed": 12,
        "Hp__1": 1,
        "Atk": 1,
        "Def": 3,
        "Spl": 1,
        "SDf": 3,
        "Spd": 1
      },
      {
        "Number": 9,
        "Name": "Blastoise",
        "HD": 14,
        "Hp": 112,
        "Type1": "Water",
        "Type2": "",
        "Health": 16,
        "Attack": 17,
        "Defense": 20,
        "Special": 17,
        "SplDef": 21,
        "Speed": 16,
        "Hp__1": 3,
        "Atk": 3,
        "Def": 5,
        "Spl": 3,
        "SDf": 5,
        "Spd": 3
      },
      {
        "Number": 10,
        "Name": "Caterpie",
        "HD": 1,
        "Hp": 4,
        "Type1": "Bug",
        "Type2": "",
        "Health": 9,
        "Attack": 6,
        "Defense": 7,
        "Special": 4,
        "SplDef": 4,
        "Speed": 9,
        "Hp__1": -1,
        "Atk": -2,
        "Def": -2,
        "Spl": -3,
        "SDf": -3,
        "Spd": -1
      },
      {
        "Number": 11,
        "Name": "Metapod",
        "HD": 1,
        "Hp": 5,
        "Type1": "Bug",
        "Type2": "",
        "Health": 10,
        "Attack": 4,
        "Defense": 11,
        "Special": 5,
        "SplDef": 5,
        "Speed": 6,
        "Hp__1": 0,
        "Atk": -3,
        "Def": 0,
        "Spl": -3,
        "SDf": -3,
        "Spd": -2
      },
      {
        "Number": 12,
        "Name": "Butterfree",
        "HD": 8,
        "Hp": 48,
        "Type1": "Bug",
        "Type2": "Flying",
        "Health": 12,
        "Attack": 9,
        "Defense": 10,
        "Special": 16,
        "SplDef": 16,
        "Speed": 14,
        "Hp__1": 1,
        "Atk": -1,
        "Def": 0,
        "Spl": 3,
        "SDf": 3,
        "Spd": 2
      },
      {
        "Number": 13,
        "Name": "Weedle",
        "HD": 1,
        "Hp": 4,
        "Type1": "Bug",
        "Type2": "Poison",
        "Health": 8,
        "Attack": 7,
        "Defense": 6,
        "Special": 4,
        "SplDef": 4,
        "Speed": 10,
        "Hp__1": -1,
        "Atk": -2,
        "Def": -2,
        "Spl": -3,
        "SDf": -3,
        "Spd": 0
      },
      {
        "Number": 14,
        "Name": "Kakuna",
        "HD": 1,
        "Hp": 4,
        "Type1": "Bug",
        "Type2": "Poison",
        "Health": 9,
        "Attack": 5,
        "Defense": 10,
        "Special": 5,
        "SplDef": 5,
        "Speed": 7,
        "Hp__1": -1,
        "Atk": -3,
        "Def": 0,
        "Spl": -3,
        "SDf": -3,
        "Spd": -2
      },
      {
        "Number": 15,
        "Name": "Beedrill",
        "HD": 8,
        "Hp": 48,
        "Type1": "Bug",
        "Type2": "Poison",
        "Health": 13,
        "Attack": 16,
        "Defense": 8,
        "Special": 9,
        "SplDef": 16,
        "Speed": 15,
        "Hp__1": 1,
        "Atk": 3,
        "Def": -1,
        "Spl": -1,
        "SDf": 3,
        "Spd": 2
      },
      {
        "Number": 16,
        "Name": "Pidgey",
        "HD": 3,
        "Hp": 12,
        "Type1": "Normal",
        "Type2": "Flying",
        "Health": 8,
        "Attack": 9,
        "Defense": 8,
        "Special": 7,
        "SplDef": 7,
        "Speed": 11,
        "Hp__1": -1,
        "Atk": -1,
        "Def": -1,
        "Spl": -2,
        "SDf": -2,
        "Spd": 0
      },
      {
        "Number": 17,
        "Name": "Pidgeotto",
        "HD": 7,
        "Hp": 42,
        "Type1": "Normal",
        "Type2": "Flying",
        "Health": 13,
        "Attack": 12,
        "Defense": 11,
        "Special": 10,
        "SplDef": 10,
        "Speed": 14,
        "Hp__1": 1,
        "Atk": 1,
        "Def": 0,
        "Spl": 0,
        "SDf": 0,
        "Spd": 2
      },
      {
        "Number": 18,
        "Name": "Pidgeot",
        "HD": 12,
        "Hp": 96,
        "Type1": "Normal",
        "Type2": "Flying",
        "Health": 17,
        "Attack": 16,
        "Defense": 15,
        "Special": 14,
        "SplDef": 14,
        "Speed": 18,
        "Hp__1": 3,
        "Atk": 3,
        "Def": 2,
        "Spl": 2,
        "SDf": 2,
        "Spd": 4
      },
      {
        "Number": 19,
        "Name": "Rattata",
        "HD": 3,
        "Hp": 9,
        "Type1": "Normal",
        "Type2": "",
        "Health": 6,
        "Attack": 11,
        "Defense": 7,
        "Special": 5,
        "SplDef": 7,
        "Speed": 14,
        "Hp__1": -2,
        "Atk": 0,
        "Def": -2,
        "Spl": -3,
        "SDf": -2,
        "Spd": 2
      },
      {
        "Number": 20,
        "Name": "Raticate",
        "HD": 9,
        "Hp": 45,
        "Type1": "Normal",
        "Type2": "",
        "Health": 11,
        "Attack": 16,
        "Defense": 12,
        "Special": 10,
        "SplDef": 14,
        "Speed": 19,
        "Hp__1": 0,
        "Atk": 3,
        "Def": 1,
        "Spl": 0,
        "SDf": 2,
        "Spd": 4
      },
      {
        "Number": 21,
        "Name": "Spearow",
        "HD": 3,
        "Hp": 12,
        "Type1": "Normal",
        "Type2": "Flying",
        "Health": 8,
        "Attack": 12,
        "Defense": 6,
        "Special": 6,
        "SplDef": 6,
        "Speed": 14,
        "Hp__1": -1,
        "Atk": 1,
        "Def": -2,
        "Spl": -2,
        "SDf": -2,
        "Spd": 2
      },
      {
        "Number": 22,
        "Name": "Fearow",
        "HD": 10,
        "Hp": 60,
        "Type1": "Normal",
        "Type2": "Flying",
        "Health": 13,
        "Attack": 18,
        "Defense": 13,
        "Special": 12,
        "SplDef": 12,
        "Speed": 20,
        "Hp__1": 1,
        "Atk": 4,
        "Def": 1,
        "Spl": 1,
        "SDf": 1,
        "Spd": 5
      },
      {
        "Number": 23,
        "Name": "Ekans",
        "HD": 4,
        "Hp": 12,
        "Type1": "Poison",
        "Type2": "",
        "Health": 7,
        "Attack": 12,
        "Defense": 9,
        "Special": 8,
        "SplDef": 11,
        "Speed": 11,
        "Hp__1": -2,
        "Atk": 1,
        "Def": -1,
        "Spl": -1,
        "SDf": 0,
        "Spd": 0
      },
      {
        "Number": 24,
        "Name": "Arbok",
        "HD": 10,
        "Hp": 60,
        "Type1": "Poison",
        "Type2": "",
        "Health": 12,
        "Attack": 17,
        "Defense": 14,
        "Special": 13,
        "SplDef": 16,
        "Speed": 16,
        "Hp__1": 1,
        "Atk": 3,
        "Def": 2,
        "Spl": 1,
        "SDf": 3,
        "Spd": 3
      },
      {
        "Number": 25,
        "Name": "Pikachu",
        "HD": 5,
        "Hp": 15,
        "Type1": "Electric",
        "Type2": "",
        "Health": 7,
        "Attack": 11,
        "Defense": 6,
        "Special": 10,
        "SplDef": 8,
        "Speed": 18,
        "Hp__1": -2,
        "Atk": 0,
        "Def": -2,
        "Spl": 0,
        "SDf": -1,
        "Spd": 4
      },
      {
        "Number": 26,
        "Name": "Raichu",
        "HD": 12,
        "Hp": 72,
        "Type1": "Electric",
        "Type2": "",
        "Health": 12,
        "Attack": 18,
        "Defense": 11,
        "Special": 18,
        "SplDef": 16,
        "Speed": 20,
        "Hp__1": 1,
        "Atk": 4,
        "Def": 0,
        "Spl": 4,
        "SDf": 3,
        "Spd": 5
      },
      {
        "Number": 27,
        "Name": "Sandshrew",
        "HD": 5,
        "Hp": 25,
        "Type1": "Ground",
        "Type2": "",
        "Health": 10,
        "Attack": 15,
        "Defense": 17,
        "Special": 4,
        "SplDef": 6,
        "Speed": 8,
        "Hp__1": 0,
        "Atk": 2,
        "Def": 3,
        "Spl": -3,
        "SDf": -2,
        "Spd": -1
      },
      {
        "Number": 28,
        "Name": "Sandslash",
        "HD": 11,
        "Hp": 77,
        "Type1": "Ground",
        "Type2": "",
        "Health": 15,
        "Attack": 20,
        "Defense": 22,
        "Special": 9,
        "SplDef": 11,
        "Speed": 13,
        "Hp__1": 2,
        "Atk": 5,
        "Def": 6,
        "Spl": -1,
        "SDf": 0,
        "Spd": 1
      },
      {
        "Number": 29,
        "Name": "Nidoran♀",
        "HD": 4,
        "Hp": 20,
        "Type1": "Poison",
        "Type2": "",
        "Health": 11,
        "Attack": 9,
        "Defense": 10,
        "Special": 8,
        "SplDef": 8,
        "Speed": 8,
        "Hp__1": 0,
        "Atk": -1,
        "Def": 0,
        "Spl": -1,
        "SDf": -1,
        "Spd": -1
      },
      {
        "Number": 30,
        "Name": "Nidorina",
        "HD": 7,
        "Hp": 49,
        "Type1": "Poison",
        "Type2": "",
        "Health": 14,
        "Attack": 12,
        "Defense": 13,
        "Special": 11,
        "SplDef": 11,
        "Speed": 11,
        "Hp__1": 2,
        "Atk": 1,
        "Def": 1,
        "Spl": 0,
        "SDf": 0,
        "Spd": 0
      },
      {
        "Number": 31,
        "Name": "Nidoqueen",
        "HD": 13,
        "Hp": 117,
        "Type1": "Poison",
        "Type2": "Ground",
        "Health": 18,
        "Attack": 16,
        "Defense": 17,
        "Special": 15,
        "SplDef": 17,
        "Speed": 15,
        "Hp__1": 4,
        "Atk": 3,
        "Def": 3,
        "Spl": 2,
        "SDf": 3,
        "Spd": 2
      },
      {
        "Number": 32,
        "Name": "Nidoran♂",
        "HD": 4,
        "Hp": 16,
        "Type1": "Poison",
        "Type2": "",
        "Health": 9,
        "Attack": 11,
        "Defense": 8,
        "Special": 8,
        "SplDef": 8,
        "Speed": 10,
        "Hp__1": -1,
        "Atk": 0,
        "Def": -1,
        "Spl": -1,
        "SDf": -1,
        "Spd": 0
      },
      {
        "Number": 33,
        "Name": "Nidorino",
        "HD": 7,
        "Hp": 42,
        "Type1": "Poison",
        "Type2": "",
        "Health": 12,
        "Attack": 14,
        "Defense": 11,
        "Special": 11,
        "SplDef": 11,
        "Speed": 13,
        "Hp__1": 1,
        "Atk": 2,
        "Def": 0,
        "Spl": 0,
        "SDf": 0,
        "Spd": 1
      },
      {
        "Number": 34,
        "Name": "Nidoking",
        "HD": 13,
        "Hp": 104,
        "Type1": "Poison",
        "Type2": "Ground",
        "Health": 16,
        "Attack": 18,
        "Defense": 15,
        "Special": 17,
        "SplDef": 15,
        "Speed": 17,
        "Hp__1": 3,
        "Atk": 4,
        "Def": 2,
        "Spl": 3,
        "SDf": 2,
        "Spd": 3
      },
      {
        "Number": 35,
        "Name": "Clefairy",
        "HD": 6,
        "Hp": 42,
        "Type1": "Fairy",
        "Type2": "",
        "Health": 14,
        "Attack": 9,
        "Defense": 10,
        "Special": 12,
        "SplDef": 13,
        "Speed": 7,
        "Hp__1": 2,
        "Atk": -1,
        "Def": 0,
        "Spl": 1,
        "SDf": 1,
        "Spd": -2
      },
      {
        "Number": 36,
        "Name": "Clefable",
        "HD": 12,
        "Hp": 108,
        "Type1": "Fairy",
        "Type2": "",
        "Health": 19,
        "Attack": 14,
        "Defense": 15,
        "Special": 17,
        "SplDef": 18,
        "Speed": 12,
        "Hp__1": 4,
        "Atk": 2,
        "Def": 2,
        "Spl": 3,
        "SDf": 4,
        "Spd": 1
      },
      {
        "Number": 37,
        "Name": "Vulpix",
        "HD": 5,
        "Hp": 20,
        "Type1": "Fire",
        "Type2": "",
        "Health": 8,
        "Attack": 8,
        "Defense": 8,
        "Special": 10,
        "SplDef": 13,
        "Speed": 13,
        "Hp__1": -1,
        "Atk": -1,
        "Def": -1,
        "Spl": 0,
        "SDf": 1,
        "Spd": 1
      },
      {
        "Number": 38,
        "Name": "Ninetales",
        "HD": 13,
        "Hp": 91,
        "Type1": "Fire",
        "Type2": "",
        "Health": 15,
        "Attack": 15,
        "Defense": 15,
        "Special": 16,
        "SplDef": 20,
        "Speed": 20,
        "Hp__1": 2,
        "Atk": 2,
        "Def": 2,
        "Spl": 3,
        "SDf": 5,
        "Spd": 5
      },
      {
        "Number": 39,
        "Name": "Jigglypuff",
        "HD": 4,
        "Hp": 44,
        "Type1": "Normal",
        "Type2": "Fairy",
        "Health": 23,
        "Attack": 9,
        "Defense": 4,
        "Special": 9,
        "SplDef": 5,
        "Speed": 4,
        "Hp__1": 6,
        "Atk": -1,
        "Def": -3,
        "Spl": -1,
        "SDf": -3,
        "Spd": -3
      },
      {
        "Number": 40,
        "Name": "Wigglytuff",
        "HD": 10,
        "Hp": 140,
        "Type1": "Normal",
        "Type2": "Fairy",
        "Health": 28,
        "Attack": 14,
        "Defense": 9,
        "Special": 15,
        "SplDef": 10,
        "Speed": 9,
        "Hp__1": 9,
        "Atk": 2,
        "Def": -1,
        "Spl": 2,
        "SDf": 0,
        "Spd": -1
      },
      {
        "Number": 41,
        "Name": "Zubat",
        "HD": 3,
        "Hp": 12,
        "Type1": "Poison",
        "Type2": "Flying",
        "Health": 8,
        "Attack": 9,
        "Defense": 7,
        "Special": 6,
        "SplDef": 8,
        "Speed": 11,
        "Hp__1": -1,
        "Atk": -1,
        "Def": -2,
        "Spl": -2,
        "SDf": -1,
        "Spd": 0
      },
      {
        "Number": 42,
        "Name": "Golbat",
        "HD": 11,
        "Hp": 77,
        "Type1": "Poison",
        "Type2": "Flying",
        "Health": 15,
        "Attack": 16,
        "Defense": 14,
        "Special": 13,
        "SplDef": 15,
        "Speed": 18,
        "Hp__1": 2,
        "Atk": 3,
        "Def": 2,
        "Spl": 1,
        "SDf": 2,
        "Spd": 4
      },
      {
        "Number": 43,
        "Name": "Oddish",
        "HD": 6,
        "Hp": 24,
        "Type1": "Grass",
        "Type2": "Poison",
        "Health": 9,
        "Attack": 10,
        "Defense": 11,
        "Special": 15,
        "SplDef": 13,
        "Speed": 6,
        "Hp__1": -1,
        "Atk": 0,
        "Def": 0,
        "Spl": 2,
        "SDf": 1,
        "Spd": -2
      },
      {
        "Number": 44,
        "Name": "Gloom",
        "HD": 9,
        "Hp": 54,
        "Type1": "Grass",
        "Type2": "Poison",
        "Health": 12,
        "Attack": 13,
        "Defense": 14,
        "Special": 17,
        "SplDef": 15,
        "Speed": 8,
        "Hp__1": 1,
        "Atk": 1,
        "Def": 2,
        "Spl": 3,
        "SDf": 2,
        "Spd": -1
      },
      {
        "Number": 45,
        "Name": "Vileplume",
        "HD": 12,
        "Hp": 84,
        "Type1": "Grass",
        "Type2": "Poison",
        "Health": 15,
        "Attack": 16,
        "Defense": 17,
        "Special": 20,
        "SplDef": 18,
        "Speed": 10,
        "Hp__1": 2,
        "Atk": 3,
        "Def": 3,
        "Spl": 5,
        "SDf": 4,
        "Spd": 0
      },
      {
        "Number": 46,
        "Name": "Paras",
        "HD": 4,
        "Hp": 12,
        "Type1": "Bug",
        "Type2": "Grass",
        "Health": 7,
        "Attack": 14,
        "Defense": 11,
        "Special": 9,
        "SplDef": 11,
        "Speed": 5,
        "Hp__1": -2,
        "Atk": 2,
        "Def": 0,
        "Spl": -1,
        "SDf": 0,
        "Spd": -3
      },
      {
        "Number": 47,
        "Name": "Parasect",
        "HD": 9,
        "Hp": 54,
        "Type1": "Bug",
        "Type2": "Grass",
        "Health": 12,
        "Attack": 19,
        "Defense": 16,
        "Special": 12,
        "SplDef": 16,
        "Speed": 6,
        "Hp__1": 1,
        "Atk": 4,
        "Def": 3,
        "Spl": 1,
        "SDf": 3,
        "Spd": -2
      },
      {
        "Number": 48,
        "Name": "Venonat",
        "HD": 5,
        "Hp": 30,
        "Type1": "Bug",
        "Type2": "Poison",
        "Health": 12,
        "Attack": 11,
        "Defense": 10,
        "Special": 8,
        "SplDef": 11,
        "Speed": 9,
        "Hp__1": 1,
        "Atk": 0,
        "Def": 0,
        "Spl": -1,
        "SDf": 0,
        "Spd": -1
      },
      {
        "Number": 49,
        "Name": "Venomoth",
        "HD": 11,
        "Hp": 77,
        "Type1": "Bug",
        "Type2": "Poison",
        "Health": 14,
        "Attack": 13,
        "Defense": 12,
        "Special": 18,
        "SplDef": 15,
        "Speed": 18,
        "Hp__1": 2,
        "Atk": 1,
        "Def": 1,
        "Spl": 4,
        "SDf": 2,
        "Spd": 4
      },
      {
        "Number": 50,
        "Name": "Diglett",
        "HD": 3,
        "Hp": 3,
        "Type1": "Ground",
        "Type2": "",
        "Health": 2,
        "Attack": 11,
        "Defense": 5,
        "Special": 7,
        "SplDef": 9,
        "Speed": 19,
        "Hp__1": -4,
        "Atk": 0,
        "Def": -3,
        "Spl": -2,
        "SDf": -1,
        "Spd": 4
      },
      {
        "Number": 51,
        "Name": "Dugtrio",
        "HD": 9,
        "Hp": 27,
        "Type1": "Ground",
        "Type2": "",
        "Health": 7,
        "Attack": 16,
        "Defense": 10,
        "Special": 10,
        "SplDef": 14,
        "Speed": 24,
        "Hp__1": -2,
        "Atk": 3,
        "Def": 0,
        "Spl": 0,
        "SDf": 2,
        "Spd": 7
      },
      {
        "Number": 52,
        "Name": "Meowth",
        "HD": 4,
        "Hp": 16,
        "Type1": "Normal",
        "Type2": "",
        "Health": 8,
        "Attack": 9,
        "Defense": 7,
        "Special": 8,
        "SplDef": 8,
        "Speed": 18,
        "Hp__1": -1,
        "Atk": -1,
        "Def": -2,
        "Spl": -1,
        "SDf": -1,
        "Spd": 4
      },
      {
        "Number": 53,
        "Name": "Persian",
        "HD": 10,
        "Hp": 60,
        "Type1": "Normal",
        "Type2": "",
        "Health": 13,
        "Attack": 14,
        "Defense": 12,
        "Special": 13,
        "SplDef": 13,
        "Speed": 23,
        "Hp__1": 1,
        "Atk": 2,
        "Def": 1,
        "Spl": 1,
        "SDf": 1,
        "Spd": 6
      },
      {
        "Number": 54,
        "Name": "Psyduck",
        "HD": 6,
        "Hp": 30,
        "Type1": "Water",
        "Type2": "",
        "Health": 10,
        "Attack": 10,
        "Defense": 10,
        "Special": 13,
        "SplDef": 10,
        "Speed": 11,
        "Hp__1": 0,
        "Atk": 0,
        "Def": 0,
        "Spl": 1,
        "SDf": 0,
        "Spd": 0
      },
      {
        "Number": 55,
        "Name": "Golduck",
        "HD": 13,
        "Hp": 104,
        "Type1": "Water",
        "Type2": "",
        "Health": 16,
        "Attack": 16,
        "Defense": 16,
        "Special": 19,
        "SplDef": 16,
        "Speed": 17,
        "Hp__1": 3,
        "Atk": 3,
        "Def": 3,
        "Spl": 4,
        "SDf": 3,
        "Spd": 3
      },
      {
        "Number": 56,
        "Name": "Mankey",
        "HD": 5,
        "Hp": 20,
        "Type1": "Fighting",
        "Type2": "",
        "Health": 8,
        "Attack": 16,
        "Defense": 7,
        "Special": 7,
        "SplDef": 9,
        "Speed": 14,
        "Hp__1": -1,
        "Atk": 3,
        "Def": -2,
        "Spl": -2,
        "SDf": -1,
        "Spd": 2
      },
      {
        "Number": 57,
        "Name": "Primeape",
        "HD": 11,
        "Hp": 66,
        "Type1": "Fighting",
        "Type2": "",
        "Health": 13,
        "Attack": 21,
        "Defense": 12,
        "Special": 12,
        "SplDef": 14,
        "Speed": 19,
        "Hp__1": 1,
        "Atk": 5,
        "Def": 1,
        "Spl": 1,
        "SDf": 2,
        "Spd": 4
      },
      {
        "Number": 58,
        "Name": "Growlithe",
        "HD": 7,
        "Hp": 35,
        "Type1": "Fire",
        "Type2": "",
        "Health": 11,
        "Attack": 14,
        "Defense": 9,
        "Special": 14,
        "SplDef": 10,
        "Speed": 12,
        "Hp__1": 0,
        "Atk": 2,
        "Def": -1,
        "Spl": 2,
        "SDf": 0,
        "Spd": 1
      },
      {
        "Number": 59,
        "Name": "Arcanine",
        "HD": 15,
        "Hp": 135,
        "Type1": "Fire",
        "Type2": "",
        "Health": 18,
        "Attack": 22,
        "Defense": 16,
        "Special": 20,
        "SplDef": 16,
        "Speed": 19,
        "Hp__1": 4,
        "Atk": 6,
        "Def": 3,
        "Spl": 5,
        "SDf": 3,
        "Spd": 4
      },
      {
        "Number": 60,
        "Name": "Poliwag",
        "HD": 5,
        "Hp": 20,
        "Type1": "Water",
        "Type2": "",
        "Health": 8,
        "Attack": 10,
        "Defense": 8,
        "Special": 8,
        "SplDef": 8,
        "Speed": 18,
        "Hp__1": -1,
        "Atk": 0,
        "Def": -1,
        "Spl": -1,
        "SDf": -1,
        "Spd": 4
      },
      {
        "Number": 61,
        "Name": "Poliwhirl",
        "HD": 8,
        "Hp": 48,
        "Type1": "Water",
        "Type2": "",
        "Health": 13,
        "Attack": 13,
        "Defense": 13,
        "Special": 10,
        "SplDef": 10,
        "Speed": 18,
        "Hp__1": 1,
        "Atk": 1,
        "Def": 1,
        "Spl": 0,
        "SDf": 0,
        "Spd": 4
      },
      {
        "Number": 62,
        "Name": "Poliwrath",
        "HD": 13,
        "Hp": 117,
        "Type1": "Water",
        "Type2": "Fighting",
        "Health": 18,
        "Attack": 17,
        "Defense": 19,
        "Special": 14,
        "SplDef": 18,
        "Speed": 14,
        "Hp__1": 4,
        "Atk": 3,
        "Def": 4,
        "Spl": 2,
        "SDf": 4,
        "Spd": 2
      },
      {
        "Number": 63,
        "Name": "Abra",
        "HD": 5,
        "Hp": 10,
        "Type1": "Psychic",
        "Type2": "",
        "Health": 5,
        "Attack": 4,
        "Defense": 3,
        "Special": 21,
        "SplDef": 11,
        "Speed": 18,
        "Hp__1": -3,
        "Atk": -3,
        "Def": -4,
        "Spl": 5,
        "SDf": 0,
        "Spd": 4
      },
      {
        "Number": 64,
        "Name": "Kadabra",
        "HD": 9,
        "Hp": 36,
        "Type1": "Psychic",
        "Type2": "",
        "Health": 8,
        "Attack": 7,
        "Defense": 6,
        "Special": 24,
        "SplDef": 14,
        "Speed": 21,
        "Hp__1": -1,
        "Atk": -2,
        "Def": -2,
        "Spl": 7,
        "SDf": 2,
        "Spd": 5
      },
      {
        "Number": 65,
        "Name": "Alakazam",
        "HD": 12,
        "Hp": 60,
        "Type1": "Psychic",
        "Type2": "",
        "Health": 11,
        "Attack": 10,
        "Defense": 9,
        "Special": 27,
        "SplDef": 17,
        "Speed": 24,
        "Hp__1": 0,
        "Atk": 0,
        "Def": -1,
        "Spl": 8,
        "SDf": 3,
        "Spd": 7
      },
      {
        "Number": 66,
        "Name": "Machop",
        "HD": 5,
        "Hp": 35,
        "Type1": "Fighting",
        "Type2": "",
        "Health": 14,
        "Attack": 16,
        "Defense": 10,
        "Special": 7,
        "SplDef": 7,
        "Speed": 7,
        "Hp__1": 2,
        "Atk": 3,
        "Def": 0,
        "Spl": -2,
        "SDf": -2,
        "Spd": -2
      },
      {
        "Number": 67,
        "Name": "Machoke",
        "HD": 9,
        "Hp": 72,
        "Type1": "Fighting",
        "Type2": "",
        "Health": 16,
        "Attack": 20,
        "Defense": 14,
        "Special": 10,
        "SplDef": 12,
        "Speed": 9,
        "Hp__1": 3,
        "Atk": 5,
        "Def": 2,
        "Spl": 0,
        "SDf": 1,
        "Spd": -1
      },
      {
        "Number": 68,
        "Name": "Machamp",
        "HD": 13,
        "Hp": 117,
        "Type1": "Fighting",
        "Type2": "",
        "Health": 18,
        "Attack": 26,
        "Defense": 16,
        "Special": 13,
        "SplDef": 17,
        "Speed": 11,
        "Hp__1": 4,
        "Atk": 8,
        "Def": 3,
        "Spl": 1,
        "SDf": 3,
        "Spd": 0
      },
      {
        "Number": 69,
        "Name": "Bellsprout",
        "HD": 5,
        "Hp": 25,
        "Type1": "Grass",
        "Type2": "Poison",
        "Health": 10,
        "Attack": 15,
        "Defense": 7,
        "Special": 14,
        "SplDef": 6,
        "Speed": 8,
        "Hp__1": 0,
        "Atk": 2,
        "Def": -2,
        "Spl": 2,
        "SDf": -2,
        "Spd": -1
      },
      {
        "Number": 70,
        "Name": "Weepinbell",
        "HD": 8,
        "Hp": 48,
        "Type1": "Grass",
        "Type2": "Poison",
        "Health": 13,
        "Attack": 18,
        "Defense": 10,
        "Special": 17,
        "SplDef": 9,
        "Speed": 11,
        "Hp__1": 1,
        "Atk": 4,
        "Def": 0,
        "Spl": 3,
        "SDf": -1,
        "Spd": 0
      },
      {
        "Number": 71,
        "Name": "Victreebel",
        "HD": 12,
        "Hp": 96,
        "Type1": "Grass",
        "Type2": "Poison",
        "Health": 16,
        "Attack": 21,
        "Defense": 13,
        "Special": 20,
        "SplDef": 12,
        "Speed": 14,
        "Hp__1": 3,
        "Atk": 5,
        "Def": 1,
        "Spl": 5,
        "SDf": 1,
        "Spd": 2
      },
      {
        "Number": 72,
        "Name": "Tentacool",
        "HD": 6,
        "Hp": 24,
        "Type1": "Water",
        "Type2": "Poison",
        "Health": 8,
        "Attack": 8,
        "Defense": 7,
        "Special": 10,
        "SplDef": 20,
        "Speed": 14,
        "Hp__1": -1,
        "Atk": -1,
        "Def": -2,
        "Spl": 0,
        "SDf": 5,
        "Spd": 2
      },
      {
        "Number": 73,
        "Name": "Tentacruel",
        "HD": 13,
        "Hp": 104,
        "Type1": "Water",
        "Type2": "Poison",
        "Health": 16,
        "Attack": 14,
        "Defense": 13,
        "Special": 16,
        "SplDef": 24,
        "Speed": 20,
        "Hp__1": 3,
        "Atk": 2,
        "Def": 1,
        "Spl": 3,
        "SDf": 7,
        "Spd": 5
      },
      {
        "Number": 74,
        "Name": "Geodude",
        "HD": 5,
        "Hp": 20,
        "Type1": "Rock",
        "Type2": "Ground",
        "Health": 8,
        "Attack": 16,
        "Defense": 20,
        "Special": 6,
        "SplDef": 6,
        "Speed": 4,
        "Hp__1": -1,
        "Atk": 3,
        "Def": 5,
        "Spl": -2,
        "SDf": -2,
        "Spd": -3
      },
      {
        "Number": 75,
        "Name": "Graveler",
        "HD": 8,
        "Hp": 40,
        "Type1": "Rock",
        "Type2": "Ground",
        "Health": 11,
        "Attack": 19,
        "Defense": 23,
        "Special": 9,
        "SplDef": 9,
        "Speed": 7,
        "Hp__1": 0,
        "Atk": 4,
        "Def": 6,
        "Spl": -1,
        "SDf": -1,
        "Spd": -2
      },
      {
        "Number": 76,
        "Name": "Golem",
        "HD": 12,
        "Hp": 96,
        "Type1": "Rock",
        "Type2": "Ground",
        "Health": 16,
        "Attack": 22,
        "Defense": 26,
        "Special": 11,
        "SplDef": 13,
        "Speed": 9,
        "Hp__1": 3,
        "Atk": 6,
        "Def": 8,
        "Spl": 0,
        "SDf": 1,
        "Spd": -1
      },
      {
        "Number": 77,
        "Name": "Ponyta",
        "HD": 9,
        "Hp": 45,
        "Type1": "Fire",
        "Type2": "",
        "Health": 10,
        "Attack": 17,
        "Defense": 11,
        "Special": 13,
        "SplDef": 13,
        "Speed": 18,
        "Hp__1": 0,
        "Atk": 3,
        "Def": 0,
        "Spl": 1,
        "SDf": 1,
        "Spd": 4
      },
      {
        "Number": 78,
        "Name": "Rapidash",
        "HD": 13,
        "Hp": 78,
        "Type1": "Fire",
        "Type2": "",
        "Health": 13,
        "Attack": 20,
        "Defense": 14,
        "Special": 16,
        "SplDef": 16,
        "Speed": 21,
        "Hp__1": 1,
        "Atk": 5,
        "Def": 2,
        "Spl": 3,
        "SDf": 3,
        "Spd": 5
      },
      {
        "Number": 79,
        "Name": "Slowpoke",
        "HD": 5,
        "Hp": 45,
        "Type1": "Water",
        "Type2": "Psychic",
        "Health": 18,
        "Attack": 13,
        "Defense": 13,
        "Special": 8,
        "SplDef": 8,
        "Speed": 3,
        "Hp__1": 4,
        "Atk": 1,
        "Def": 1,
        "Spl": -1,
        "SDf": -1,
        "Spd": -4
      },
      {
        "Number": 80,
        "Name": "Slowbro",
        "HD": 12,
        "Hp": 108,
        "Type1": "Water",
        "Type2": "Psychic",
        "Health": 19,
        "Attack": 15,
        "Defense": 22,
        "Special": 20,
        "SplDef": 16,
        "Speed": 6,
        "Hp__1": 4,
        "Atk": 2,
        "Def": 6,
        "Spl": 5,
        "SDf": 3,
        "Spd": -2
      },
      {
        "Number": 81,
        "Name": "Magnemite",
        "HD": 6,
        "Hp": 12,
        "Type1": "Electric",
        "Type2": "Steel",
        "Health": 5,
        "Attack": 7,
        "Defense": 14,
        "Special": 19,
        "SplDef": 11,
        "Speed": 9,
        "Hp__1": -3,
        "Atk": -2,
        "Def": 2,
        "Spl": 4,
        "SDf": 0,
        "Spd": -1
      },
      {
        "Number": 82,
        "Name": "Magneton",
        "HD": 11,
        "Hp": 55,
        "Type1": "Electric",
        "Type2": "Steel",
        "Health": 10,
        "Attack": 12,
        "Defense": 19,
        "Special": 24,
        "SplDef": 14,
        "Speed": 14,
        "Hp__1": 0,
        "Atk": 1,
        "Def": 4,
        "Spl": 7,
        "SDf": 2,
        "Spd": 2
      },
      {
        "Number": 83,
        "Name": "Farfetch'd",
        "HD": 7,
        "Hp": 35,
        "Type1": "Normal",
        "Type2": "Flying",
        "Health": 10,
        "Attack": 13,
        "Defense": 11,
        "Special": 12,
        "SplDef": 12,
        "Speed": 12,
        "Hp__1": 0,
        "Atk": 1,
        "Def": 0,
        "Spl": 1,
        "SDf": 1,
        "Spd": 1
      },
      {
        "Number": 84,
        "Name": "Doduo",
        "HD": 5,
        "Hp": 15,
        "Type1": "Normal",
        "Type2": "Flying",
        "Health": 7,
        "Attack": 17,
        "Defense": 9,
        "Special": 7,
        "SplDef": 7,
        "Speed": 15,
        "Hp__1": -2,
        "Atk": 3,
        "Def": -1,
        "Spl": -2,
        "SDf": -2,
        "Spd": 2
      },
      {
        "Number": 85,
        "Name": "Dodrio",
        "HD": 11,
        "Hp": 66,
        "Type1": "Normal",
        "Type2": "Flying",
        "Health": 12,
        "Attack": 22,
        "Defense": 14,
        "Special": 12,
        "SplDef": 12,
        "Speed": 20,
        "Hp__1": 1,
        "Atk": 6,
        "Def": 2,
        "Spl": 1,
        "SDf": 1,
        "Spd": 5
      },
      {
        "Number": 86,
        "Name": "Seel",
        "HD": 6,
        "Hp": 36,
        "Type1": "Water",
        "Type2": "",
        "Health": 13,
        "Attack": 9,
        "Defense": 11,
        "Special": 9,
        "SplDef": 14,
        "Speed": 9,
        "Hp__1": 1,
        "Atk": -1,
        "Def": 0,
        "Spl": -1,
        "SDf": 2,
        "Spd": -1
      },
      {
        "Number": 87,
        "Name": "Dewgong",
        "HD": 12,
        "Hp": 108,
        "Type1": "Water",
        "Type2": "Ice",
        "Health": 18,
        "Attack": 14,
        "Defense": 16,
        "Special": 14,
        "SplDef": 19,
        "Speed": 14,
        "Hp__1": 4,
        "Atk": 2,
        "Def": 3,
        "Spl": 2,
        "SDf": 4,
        "Spd": 2
      },
      {
        "Number": 88,
        "Name": "Grimer",
        "HD": 6,
        "Hp": 48,
        "Type1": "Poison",
        "Type2": "",
        "Health": 16,
        "Attack": 16,
        "Defense": 10,
        "Special": 8,
        "SplDef": 10,
        "Speed": 5,
        "Hp__1": 3,
        "Atk": 3,
        "Def": 0,
        "Spl": -1,
        "SDf": 0,
        "Spd": -3
      },
      {
        "Number": 89,
        "Name": "Muk",
        "HD": 13,
        "Hp": 130,
        "Type1": "Poison",
        "Type2": "",
        "Health": 21,
        "Attack": 21,
        "Defense": 15,
        "Special": 13,
        "SplDef": 20,
        "Speed": 10,
        "Hp__1": 5,
        "Atk": 5,
        "Def": 2,
        "Spl": 1,
        "SDf": 5,
        "Spd": 0
      },
      {
        "Number": 90,
        "Name": "Shellder",
        "HD": 5,
        "Hp": 15,
        "Type1": "Water",
        "Type2": "",
        "Health": 6,
        "Attack": 13,
        "Defense": 20,
        "Special": 9,
        "SplDef": 5,
        "Speed": 8,
        "Hp__1": -2,
        "Atk": 1,
        "Def": 5,
        "Spl": -1,
        "SDf": -3,
        "Spd": -1
      },
      {
        "Number": 91,
        "Name": "Cloyster",
        "HD": 14,
        "Hp": 70,
        "Type1": "Water",
        "Type2": "Ice",
        "Health": 10,
        "Attack": 19,
        "Defense": 36,
        "Special": 17,
        "SplDef": 9,
        "Speed": 14,
        "Hp__1": 0,
        "Atk": 4,
        "Def": 13,
        "Spl": 3,
        "SDf": -1,
        "Spd": 2
      },
      {
        "Number": 92,
        "Name": "Gastly",
        "HD": 5,
        "Hp": 15,
        "Type1": "Ghost",
        "Type2": "Poison",
        "Health": 6,
        "Attack": 7,
        "Defense": 6,
        "Special": 20,
        "SplDef": 7,
        "Speed": 16,
        "Hp__1": -2,
        "Atk": -2,
        "Def": -2,
        "Spl": 5,
        "SDf": -2,
        "Spd": 3
      },
      {
        "Number": 93,
        "Name": "Haunter",
        "HD": 9,
        "Hp": 36,
        "Type1": "Ghost",
        "Type2": "Poison",
        "Health": 9,
        "Attack": 10,
        "Defense": 9,
        "Special": 23,
        "SplDef": 11,
        "Speed": 19,
        "Hp__1": -1,
        "Atk": 0,
        "Def": -1,
        "Spl": 6,
        "SDf": 0,
        "Spd": 4
      },
      {
        "Number": 94,
        "Name": "Gengar",
        "HD": 13,
        "Hp": 78,
        "Type1": "Ghost",
        "Type2": "Poison",
        "Health": 12,
        "Attack": 13,
        "Defense": 12,
        "Special": 26,
        "SplDef": 15,
        "Speed": 22,
        "Hp__1": 1,
        "Atk": 1,
        "Def": 1,
        "Spl": 8,
        "SDf": 2,
        "Spd": 6
      },
      {
        "Number": 95,
        "Name": "Onix",
        "HD": 8,
        "Hp": 24,
        "Type1": "Rock",
        "Type2": "Ground",
        "Health": 7,
        "Attack": 9,
        "Defense": 32,
        "Special": 6,
        "SplDef": 9,
        "Speed": 14,
        "Hp__1": -2,
        "Atk": -1,
        "Def": 11,
        "Spl": -2,
        "SDf": -1,
        "Spd": 2
      },
      {
        "Number": 96,
        "Name": "Drowzee",
        "HD": 6,
        "Hp": 36,
        "Type1": "Psychic",
        "Type2": "",
        "Health": 12,
        "Attack": 10,
        "Defense": 9,
        "Special": 9,
        "SplDef": 18,
        "Speed": 8,
        "Hp__1": 1,
        "Atk": 0,
        "Def": -1,
        "Spl": -1,
        "SDf": 4,
        "Spd": -1
      },
      {
        "Number": 97,
        "Name": "Hypno",
        "HD": 12,
        "Hp": 96,
        "Type1": "Psychic",
        "Type2": "",
        "Health": 17,
        "Attack": 15,
        "Defense": 14,
        "Special": 15,
        "SplDef": 23,
        "Speed": 13,
        "Hp__1": 3,
        "Atk": 2,
        "Def": 2,
        "Spl": 2,
        "SDf": 6,
        "Spd": 1
      },
      {
        "Number": 98,
        "Name": "Krabby",
        "HD": 6,
        "Hp": 18,
        "Type1": "Water",
        "Type2": "",
        "Health": 6,
        "Attack": 21,
        "Defense": 18,
        "Special": 5,
        "SplDef": 5,
        "Speed": 10,
        "Hp__1": -2,
        "Atk": 5,
        "Def": 4,
        "Spl": -3,
        "SDf": -3,
        "Spd": 0
      },
      {
        "Number": 99,
        "Name": "Kingler",
        "HD": 12,
        "Hp": 60,
        "Type1": "Water",
        "Type2": "",
        "Health": 11,
        "Attack": 26,
        "Defense": 23,
        "Special": 10,
        "SplDef": 10,
        "Speed": 15,
        "Hp__1": 0,
        "Atk": 8,
        "Def": 6,
        "Spl": 0,
        "SDf": 0,
        "Spd": 2
      },
      {
        "Number": 100,
        "Name": "Voltorb",
        "HD": 6,
        "Hp": 24,
        "Type1": "Electric",
        "Type2": "",
        "Health": 8,
        "Attack": 6,
        "Defense": 10,
        "Special": 11,
        "SplDef": 11,
        "Speed": 20,
        "Hp__1": -1,
        "Atk": -2,
        "Def": 0,
        "Spl": 0,
        "SDf": 0,
        "Spd": 5
      },
      {
        "Number": 101,
        "Name": "Electrode",
        "HD": 12,
        "Hp": 72,
        "Type1": "Electric",
        "Type2": "",
        "Health": 12,
        "Attack": 10,
        "Defense": 14,
        "Special": 16,
        "SplDef": 16,
        "Speed": 28,
        "Hp__1": 1,
        "Atk": 0,
        "Def": 2,
        "Spl": 3,
        "SDf": 3,
        "Spd": 9
      },
      {
        "Number": 102,
        "Name": "Exeggcute",
        "HD": 6,
        "Hp": 36,
        "Type1": "Grass",
        "Type2": "Psychic",
        "Health": 12,
        "Attack": 8,
        "Defense": 16,
        "Special": 12,
        "SplDef": 9,
        "Speed": 8,
        "Hp__1": 1,
        "Atk": -1,
        "Def": 3,
        "Spl": 1,
        "SDf": -1,
        "Spd": -1
      },
      {
        "Number": 103,
        "Name": "Exeggutor",
        "HD": 14,
        "Hp": 126,
        "Type1": "Grass",
        "Type2": "Psychic",
        "Health": 19,
        "Attack": 19,
        "Defense": 17,
        "Special": 25,
        "SplDef": 13,
        "Speed": 11,
        "Hp__1": 4,
        "Atk": 4,
        "Def": 3,
        "Spl": 7,
        "SDf": 1,
        "Spd": 0
      },
      {
        "Number": 104,
        "Name": "Cubone",
        "HD": 6,
        "Hp": 30,
        "Type1": "Ground",
        "Type2": "",
        "Health": 10,
        "Attack": 10,
        "Defense": 19,
        "Special": 8,
        "SplDef": 10,
        "Speed": 7,
        "Hp__1": 0,
        "Atk": 0,
        "Def": 4,
        "Spl": -1,
        "SDf": 0,
        "Spd": -2
      },
      {
        "Number": 105,
        "Name": "Marowak",
        "HD": 10,
        "Hp": 60,
        "Type1": "Ground",
        "Type2": "",
        "Health": 12,
        "Attack": 16,
        "Defense": 22,
        "Special": 10,
        "SplDef": 16,
        "Speed": 9,
        "Hp__1": 1,
        "Atk": 3,
        "Def": 6,
        "Spl": 0,
        "SDf": 3,
        "Spd": -1
      },
      {
        "Number": 106,
        "Name": "Hitmonlee",
        "HD": 11,
        "Hp": 55,
        "Type1": "Fighting",
        "Type2": "",
        "Health": 10,
        "Attack": 24,
        "Defense": 11,
        "Special": 7,
        "SplDef": 22,
        "Speed": 17,
        "Hp__1": 0,
        "Atk": 7,
        "Def": 0,
        "Spl": -2,
        "SDf": 6,
        "Spd": 3
      },
      {
        "Number": 107,
        "Name": "Hitmonchan",
        "HD": 11,
        "Hp": 55,
        "Type1": "Fighting",
        "Type2": "",
        "Health": 10,
        "Attack": 21,
        "Defense": 16,
        "Special": 7,
        "SplDef": 22,
        "Speed": 15,
        "Hp__1": 0,
        "Atk": 5,
        "Def": 3,
        "Spl": -2,
        "SDf": 6,
        "Spd": 2
      },
      {
        "Number": 108,
        "Name": "Lickitung",
        "HD": 8,
        "Hp": 72,
        "Type1": "Normal",
        "Type2": "",
        "Health": 18,
        "Attack": 11,
        "Defense": 15,
        "Special": 12,
        "SplDef": 15,
        "Speed": 6,
        "Hp__1": 4,
        "Atk": 0,
        "Def": 2,
        "Spl": 1,
        "SDf": 2,
        "Spd": -2
      },
      {
        "Number": 109,
        "Name": "Koffing",
        "HD": 6,
        "Hp": 24,
        "Type1": "Poison",
        "Type2": "",
        "Health": 8,
        "Attack": 13,
        "Defense": 19,
        "Special": 12,
        "SplDef": 9,
        "Speed": 7,
        "Hp__1": -1,
        "Atk": 1,
        "Def": 4,
        "Spl": 1,
        "SDf": -1,
        "Spd": -2
      },
      {
        "Number": 110,
        "Name": "Weezing",
        "HD": 12,
        "Hp": 72,
        "Type1": "Poison",
        "Type2": "",
        "Health": 13,
        "Attack": 18,
        "Defense": 24,
        "Special": 17,
        "SplDef": 14,
        "Speed": 12,
        "Hp__1": 1,
        "Atk": 4,
        "Def": 7,
        "Spl": 3,
        "SDf": 2,
        "Spd": 1
      },
      {
        "Number": 111,
        "Name": "Rhyhorn",
        "HD": 7,
        "Hp": 56,
        "Type1": "Ground",
        "Type2": "Rock",
        "Health": 16,
        "Attack": 17,
        "Defense": 19,
        "Special": 6,
        "SplDef": 6,
        "Speed": 5,
        "Hp__1": 3,
        "Atk": 3,
        "Def": 4,
        "Spl": -2,
        "SDf": -2,
        "Spd": -3
      },
      {
        "Number": 112,
        "Name": "Rhydon",
        "HD": 12,
        "Hp": 120,
        "Type1": "Ground",
        "Type2": "Rock",
        "Health": 21,
        "Attack": 26,
        "Defense": 24,
        "Special": 9,
        "SplDef": 9,
        "Speed": 8,
        "Hp__1": 5,
        "Atk": 8,
        "Def": 7,
        "Spl": -1,
        "SDf": -1,
        "Spd": -1
      },
      {
        "Number": 113,
        "Name": "Chansey",
        "HD": 11,
        "Hp": 275,
        "Type1": "Normal",
        "Type2": "",
        "Health": 50,
        "Attack": 1,
        "Defense": 1,
        "Special": 7,
        "SplDef": 21,
        "Speed": 10,
        "Hp__1": 20,
        "Atk": -5,
        "Def": -5,
        "Spl": -2,
        "SDf": 5,
        "Spd": 0
      },
      {
        "Number": 114,
        "Name": "Tangela",
        "HD": 10,
        "Hp": 60,
        "Type1": "Grass",
        "Type2": "",
        "Health": 13,
        "Attack": 11,
        "Defense": 23,
        "Special": 20,
        "SplDef": 8,
        "Speed": 12,
        "Hp__1": 1,
        "Atk": 0,
        "Def": 6,
        "Spl": 5,
        "SDf": -1,
        "Spd": 1
      },
      {
        "Number": 115,
        "Name": "Kangaskhan",
        "HD": 12,
        "Hp": 120,
        "Type1": "Normal",
        "Type2": "",
        "Health": 21,
        "Attack": 19,
        "Defense": 16,
        "Special": 8,
        "SplDef": 16,
        "Speed": 18,
        "Hp__1": 5,
        "Atk": 4,
        "Def": 3,
        "Spl": -1,
        "SDf": 3,
        "Spd": 4
      },
      {
        "Number": 116,
        "Name": "Horsea",
        "HD": 5,
        "Hp": 15,
        "Type1": "Water",
        "Type2": "",
        "Health": 6,
        "Attack": 8,
        "Defense": 14,
        "Special": 14,
        "SplDef": 5,
        "Speed": 12,
        "Hp__1": -2,
        "Atk": -1,
        "Def": 2,
        "Spl": 2,
        "SDf": -3,
        "Spd": 1
      },
      {
        "Number": 117,
        "Name": "Seadra",
        "HD": 10,
        "Hp": 50,
        "Type1": "Water",
        "Type2": "",
        "Health": 11,
        "Attack": 13,
        "Defense": 19,
        "Special": 19,
        "SplDef": 9,
        "Speed": 17,
        "Hp__1": 0,
        "Atk": 1,
        "Def": 4,
        "Spl": 4,
        "SDf": -1,
        "Spd": 3
      },
      {
        "Number": 118,
        "Name": "Goldeen",
        "HD": 6,
        "Hp": 24,
        "Type1": "Water",
        "Type2": "",
        "Health": 9,
        "Attack": 13,
        "Defense": 12,
        "Special": 7,
        "SplDef": 10,
        "Speed": 13,
        "Hp__1": -1,
        "Atk": 1,
        "Def": 1,
        "Spl": -2,
        "SDf": 0,
        "Spd": 1
      },
      {
        "Number": 119,
        "Name": "Seaking",
        "HD": 11,
        "Hp": 88,
        "Type1": "Water",
        "Type2": "",
        "Health": 16,
        "Attack": 18,
        "Defense": 13,
        "Special": 13,
        "SplDef": 16,
        "Speed": 14,
        "Hp__1": 3,
        "Atk": 4,
        "Def": 1,
        "Spl": 1,
        "SDf": 3,
        "Spd": 2
      },
      {
        "Number": 120,
        "Name": "Staryu",
        "HD": 6,
        "Hp": 18,
        "Type1": "Water",
        "Type2": "",
        "Health": 6,
        "Attack": 9,
        "Defense": 11,
        "Special": 14,
        "SplDef": 11,
        "Speed": 17,
        "Hp__1": -2,
        "Atk": -1,
        "Def": 0,
        "Spl": 2,
        "SDf": 0,
        "Spd": 3
      },
      {
        "Number": 121,
        "Name": "Starmie",
        "HD": 14,
        "Hp": 84,
        "Type1": "Water",
        "Type2": "Psychic",
        "Health": 12,
        "Attack": 15,
        "Defense": 17,
        "Special": 20,
        "SplDef": 17,
        "Speed": 23,
        "Hp__1": 1,
        "Atk": 2,
        "Def": 3,
        "Spl": 5,
        "SDf": 3,
        "Spd": 6
      },
      {
        "Number": 122,
        "Name": "Mr. Mime",
        "HD": 11,
        "Hp": 44,
        "Type1": "Psychic",
        "Type2": "Fairy",
        "Health": 8,
        "Attack": 9,
        "Defense": 13,
        "Special": 20,
        "SplDef": 24,
        "Speed": 18,
        "Hp__1": -1,
        "Atk": -1,
        "Def": 1,
        "Spl": 5,
        "SDf": 7,
        "Spd": 4
      },
      {
        "Number": 123,
        "Name": "Scyther",
        "HD": 13,
        "Hp": 91,
        "Type1": "Bug",
        "Type2": "Flying",
        "Health": 14,
        "Attack": 22,
        "Defense": 16,
        "Special": 11,
        "SplDef": 16,
        "Speed": 21,
        "Hp__1": 2,
        "Atk": 6,
        "Def": 3,
        "Spl": 0,
        "SDf": 3,
        "Spd": 5
      },
      {
        "Number": 124,
        "Name": "Jynx",
        "HD": 11,
        "Hp": 66,
        "Type1": "Ice",
        "Type2": "Psychic",
        "Health": 13,
        "Attack": 10,
        "Defense": 7,
        "Special": 23,
        "SplDef": 19,
        "Speed": 19,
        "Hp__1": 1,
        "Atk": 0,
        "Def": -2,
        "Spl": 6,
        "SDf": 4,
        "Spd": 4
      },
      {
        "Number": 125,
        "Name": "Electabuzz",
        "HD": 12,
        "Hp": 72,
        "Type1": "Electric",
        "Type2": "",
        "Health": 13,
        "Attack": 17,
        "Defense": 11,
        "Special": 19,
        "SplDef": 17,
        "Speed": 21,
        "Hp__1": 1,
        "Atk": 3,
        "Def": 0,
        "Spl": 4,
        "SDf": 3,
        "Spd": 5
      },
      {
        "Number": 126,
        "Name": "Magmar",
        "HD": 13,
        "Hp": 78,
        "Type1": "Fire",
        "Type2": "",
        "Health": 13,
        "Attack": 19,
        "Defense": 11,
        "Special": 20,
        "SplDef": 17,
        "Speed": 19,
        "Hp__1": 1,
        "Atk": 4,
        "Def": 0,
        "Spl": 5,
        "SDf": 3,
        "Spd": 4
      },
      {
        "Number": 127,
        "Name": "Pinsir",
        "HD": 13,
        "Hp": 78,
        "Type1": "Bug",
        "Type2": "",
        "Health": 13,
        "Attack": 25,
        "Defense": 20,
        "Special": 11,
        "SplDef": 14,
        "Speed": 17,
        "Hp__1": 1,
        "Atk": 7,
        "Def": 5,
        "Spl": 0,
        "SDf": 2,
        "Spd": 3
      },
      {
        "Number": 128,
        "Name": "Tauros",
        "HD": 12,
        "Hp": 84,
        "Type1": "Normal",
        "Type2": "",
        "Health": 15,
        "Attack": 20,
        "Defense": 19,
        "Special": 8,
        "SplDef": 14,
        "Speed": 22,
        "Hp__1": 2,
        "Atk": 5,
        "Def": 4,
        "Spl": -1,
        "SDf": 2,
        "Spd": 6
      },
      {
        "Number": 129,
        "Name": "Magikarp",
        "HD": 1,
        "Hp": 2,
        "Type1": "Water",
        "Type2": "",
        "Health": 4,
        "Attack": 2,
        "Defense": 11,
        "Special": 3,
        "SplDef": 4,
        "Speed": 16,
        "Hp__1": -3,
        "Atk": -4,
        "Def": 0,
        "Spl": -4,
        "SDf": -3,
        "Spd": 3
      },
      {
        "Number": 130,
        "Name": "Gyarados",
        "HD": 14,
        "Hp": 126,
        "Type1": "Water",
        "Type2": "Flying",
        "Health": 19,
        "Attack": 25,
        "Defense": 16,
        "Special": 12,
        "SplDef": 20,
        "Speed": 16,
        "Hp__1": 4,
        "Atk": 7,
        "Def": 3,
        "Spl": 1,
        "SDf": 5,
        "Spd": 3
      },
      {
        "Number": 131,
        "Name": "Lapras",
        "HD": 14,
        "Hp": 182,
        "Type1": "Water",
        "Type2": "Ice",
        "Health": 26,
        "Attack": 17,
        "Defense": 16,
        "Special": 17,
        "SplDef": 19,
        "Speed": 12,
        "Hp__1": 8,
        "Atk": 3,
        "Def": 3,
        "Spl": 3,
        "SDf": 4,
        "Spd": 1
      },
      {
        "Number": 132,
        "Name": "Ditto",
        "HD": 4,
        "Hp": 20,
        "Type1": "Normal",
        "Type2": "",
        "Health": 10,
        "Attack": 10,
        "Defense": 10,
        "Special": 10,
        "SplDef": 10,
        "Speed": 10,
        "Hp__1": 0,
        "Atk": 0,
        "Def": 0,
        "Spl": 0,
        "SDf": 0,
        "Spd": 0
      },
      {
        "Number": 133,
        "Name": "Eevee",
        "HD": 6,
        "Hp": 30,
        "Type1": "Normal",
        "Type2": "",
        "Health": 11,
        "Attack": 11,
        "Defense": 10,
        "Special": 9,
        "SplDef": 13,
        "Speed": 11,
        "Hp__1": 0,
        "Atk": 0,
        "Def": 0,
        "Spl": -1,
        "SDf": 1,
        "Spd": 0
      },
      {
        "Number": 134,
        "Name": "Vaporeon",
        "HD": 14,
        "Hp": 182,
        "Type1": "Water",
        "Type2": "",
        "Health": 26,
        "Attack": 13,
        "Defense": 12,
        "Special": 22,
        "SplDef": 19,
        "Speed": 13,
        "Hp__1": 8,
        "Atk": 1,
        "Def": 1,
        "Spl": 6,
        "SDf": 4,
        "Spd": 1
      },
      {
        "Number": 135,
        "Name": "Jolteon",
        "HD": 14,
        "Hp": 84,
        "Type1": "Electric",
        "Type2": "",
        "Health": 13,
        "Attack": 13,
        "Defense": 12,
        "Special": 22,
        "SplDef": 19,
        "Speed": 26,
        "Hp__1": 1,
        "Atk": 1,
        "Def": 1,
        "Spl": 6,
        "SDf": 4,
        "Spd": 8
      },
      {
        "Number": 136,
        "Name": "Flareon",
        "HD": 14,
        "Hp": 84,
        "Type1": "Fire",
        "Type2": "",
        "Health": 13,
        "Attack": 26,
        "Defense": 12,
        "Special": 19,
        "SplDef": 22,
        "Speed": 13,
        "Hp__1": 1,
        "Atk": 8,
        "Def": 1,
        "Spl": 4,
        "SDf": 6,
        "Spd": 1
      },
      {
        "Number": 137,
        "Name": "Porygon",
        "HD": 9,
        "Hp": 54,
        "Type1": "Normal",
        "Type2": "",
        "Health": 13,
        "Attack": 12,
        "Defense": 14,
        "Special": 17,
        "SplDef": 15,
        "Speed": 8,
        "Hp__1": 1,
        "Atk": 1,
        "Def": 2,
        "Spl": 3,
        "SDf": 2,
        "Spd": -1
      },
      {
        "Number": 138,
        "Name": "Omanyte",
        "HD": 7,
        "Hp": 21,
        "Type1": "Rock",
        "Type2": "Water",
        "Health": 7,
        "Attack": 8,
        "Defense": 20,
        "Special": 18,
        "SplDef": 11,
        "Speed": 7,
        "Hp__1": -2,
        "Atk": -1,
        "Def": 5,
        "Spl": 4,
        "SDf": 0,
        "Spd": -2
      },
      {
        "Number": 139,
        "Name": "Omastar",
        "HD": 13,
        "Hp": 91,
        "Type1": "Rock",
        "Type2": "Water",
        "Health": 14,
        "Attack": 12,
        "Defense": 25,
        "Special": 23,
        "SplDef": 14,
        "Speed": 11,
        "Hp__1": 2,
        "Atk": 1,
        "Def": 7,
        "Spl": 6,
        "SDf": 2,
        "Spd": 0
      },
      {
        "Number": 140,
        "Name": "Kabuto",
        "HD": 7,
        "Hp": 21,
        "Type1": "Rock",
        "Type2": "Water",
        "Health": 6,
        "Attack": 16,
        "Defense": 18,
        "Special": 11,
        "SplDef": 9,
        "Speed": 11,
        "Hp__1": -2,
        "Atk": 3,
        "Def": 4,
        "Spl": 0,
        "SDf": -1,
        "Spd": 0
      },
      {
        "Number": 141,
        "Name": "Kabutops",
        "HD": 13,
        "Hp": 78,
        "Type1": "Rock",
        "Type2": "Water",
        "Health": 12,
        "Attack": 23,
        "Defense": 21,
        "Special": 13,
        "SplDef": 14,
        "Speed": 16,
        "Hp__1": 1,
        "Atk": 6,
        "Def": 5,
        "Spl": 1,
        "SDf": 2,
        "Spd": 3
      },
      {
        "Number": 142,
        "Name": "Aerodactyl",
        "HD": 13,
        "Hp": 104,
        "Type1": "Rock",
        "Type2": "Flying",
        "Health": 16,
        "Attack": 21,
        "Defense": 13,
        "Special": 12,
        "SplDef": 15,
        "Speed": 26,
        "Hp__1": 3,
        "Atk": 5,
        "Def": 1,
        "Spl": 1,
        "SDf": 2,
        "Spd": 8
      },
      {
        "Number": 143,
        "Name": "Snorlax",
        "HD": 14,
        "Hp": 224,
        "Type1": "Normal",
        "Type2": "",
        "Health": 32,
        "Attack": 22,
        "Defense": 13,
        "Special": 13,
        "SplDef": 22,
        "Speed": 6,
        "Hp__1": 11,
        "Atk": 6,
        "Def": 1,
        "Spl": 1,
        "SDf": 6,
        "Spd": -2
      },
      {
        "Number": 144,
        "Name": "Articuno",
        "HD": 16,
        "Hp": 144,
        "Type1": "Ice",
        "Type2": "Flying",
        "Health": 18,
        "Attack": 17,
        "Defense": 20,
        "Special": 19,
        "SplDef": 25,
        "Speed": 17,
        "Hp__1": 4,
        "Atk": 3,
        "Def": 5,
        "Spl": 4,
        "SDf": 7,
        "Spd": 3
      },
      {
        "Number": 145,
        "Name": "Zapdos",
        "HD": 16,
        "Hp": 144,
        "Type1": "Electric",
        "Type2": "Flying",
        "Health": 18,
        "Attack": 18,
        "Defense": 17,
        "Special": 25,
        "SplDef": 18,
        "Speed": 20,
        "Hp__1": 4,
        "Atk": 4,
        "Def": 3,
        "Spl": 7,
        "SDf": 4,
        "Spd": 5
      },
      {
        "Number": 146,
        "Name": "Moltres",
        "HD": 16,
        "Hp": 144,
        "Type1": "Fire",
        "Type2": "Flying",
        "Health": 18,
        "Attack": 20,
        "Defense": 18,
        "Special": 25,
        "SplDef": 17,
        "Speed": 18,
        "Hp__1": 4,
        "Atk": 5,
        "Def": 4,
        "Spl": 7,
        "SDf": 3,
        "Spd": 4
      },
      {
        "Number": 147,
        "Name": "Dratini",
        "HD": 5,
        "Hp": 20,
        "Type1": "Dragon",
        "Type2": "",
        "Health": 8,
        "Attack": 13,
        "Defense": 9,
        "Special": 10,
        "SplDef": 10,
        "Speed": 10,
        "Hp__1": -1,
        "Atk": 1,
        "Def": -1,
        "Spl": 0,
        "SDf": 0,
        "Spd": 0
      },
      {
        "Number": 148,
        "Name": "Dragonair",
        "HD": 10,
        "Hp": 60,
        "Type1": "Dragon",
        "Type2": "",
        "Health": 12,
        "Attack": 17,
        "Defense": 13,
        "Special": 14,
        "SplDef": 14,
        "Speed": 14,
        "Hp__1": 1,
        "Atk": 3,
        "Def": 1,
        "Spl": 2,
        "SDf": 2,
        "Spd": 2
      },
      {
        "Number": 149,
        "Name": "Dragonite",
        "HD": 17,
        "Hp": 153,
        "Type1": "Dragon",
        "Type2": "Flying",
        "Health": 18,
        "Attack": 27,
        "Defense": 19,
        "Special": 20,
        "SplDef": 20,
        "Speed": 16,
        "Hp__1": 4,
        "Atk": 8,
        "Def": 4,
        "Spl": 5,
        "SDf": 5,
        "Spd": 3
      },
      {
        "Number": 150,
        "Name": "Mewtwo",
        "HD": 20,
        "Hp": 200,
        "Type1": "Psychic",
        "Type2": "",
        "Health": 21,
        "Attack": 22,
        "Defense": 18,
        "Special": 31,
        "SplDef": 18,
        "Speed": 26,
        "Hp__1": 5,
        "Atk": 6,
        "Def": 4,
        "Spl": 10,
        "SDf": 4,
        "Spd": 8
      },
      {
        "Number": 151,
        "Name": "Mew",
        "HD": 17,
        "Hp": 170,
        "Type1": "Psychic",
        "Type2": "",
        "Health": 20,
        "Attack": 20,
        "Defense": 20,
        "Special": 20,
        "SplDef": 20,
        "Speed": 20,
        "Hp__1": 5,
        "Atk": 5,
        "Def": 5,
        "Spl": 5,
        "SDf": 5,
        "Spd": 5
      }
    ]
  }
}